### ISSUE TITLE
Typo 152 "BackgroundColor=Red"

### ISSUE THREAD

**Issue by Lairo** [head-first-csharp/fifth-edition#4]
In the book and Pdf (not in git upload though) the page states 
"BackgroundColor=Red"

The colour stated to be utilised in the PDF (it is in colour) and in print #4d2dcc

![image](https://github.com/user-attachments/assets/67a17d88-114c-4048-8f5b-e80eda8bd516)

**Comment by andrewstellman** [comment]
Oops! Thanks for finding that, I'll make sure it gets fixed.
