### ISSUE TITLE
Warning message from MainPage() 

### ISSUE THREAD

**Issue by mohawk1df** [head-first-csharp/fifth-edition#8]
After adding the code for the Button_Clicked event VS 2022 Comm. displayed the following warning message: "Non-nullable field 'lastClicked' must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring the field as nullable."

How do you suggest correcting the code to eliminate this message?

**Comment by andrewstellman** [comment]
Thanks for pointing this out. I meant to include this comment on that page, but it accidentally got deleted:

"Did you notice a warning about a non-nullable field? Your code will still run, and you don't need to fix it for now. You'll learn about what this means and how to fix it in Chapter 11."

I'll make sure that gets updated in future editions.
